### ISSUE TITLE
On submit hanging 

### ISSUE THREAD

**Issue by tomolopolis** [CogStack/MedCATtrainer#19]
Users experiencing on submit hanging at confirm stage, seems to suggest there is an error from the middle tier. Surface these errors on the front for easier debugging

**Comment by sandertan** [comment]
Perhaps related to this: When selecting an unsubmitted annotated document, the first time after I click Submit I see all only the concept ID of the first term, and the Submitting document button hangs:

![Screenshot 2020-09-24 at 12 24 53](https://user-images.githubusercontent.com/9624990/94133492-02c57800-fe61-11ea-9ec6-2c2d39092734.png)

After manually closing the window and clicking Submit again, all concept IDs show up, but the Submitting Document button still hangs.
![Screenshot 2020-09-24 at 12 25 07](https://user-images.githubusercontent.com/9624990/94133551-17097500-fe61-11ea-923e-ae4a9af62c80.png)

**Comment by sandertan** [comment]
I just found out, that when the button is hanging and I refresh the page, the document gets the checkmark.

**Comment by tomolopolis** [comment]
This sounds like its succeeding on the backend but failing to process that
on the front end. Are you using a combination of the click submit and
'enter' shortcut to confirm? or visa versa?

**Comment by tomolopolis** [comment]
I fixed the submit hanging on the final document here: https://github.com/CogStack/MedCATtrainer/commit/109c25fb4446e7b3503b2b538892da7f39cdee5d

I couldn't repro in any other instance. The submit can take a couple some time (say up to 10 seconds) as it also loads the next document to annotate, especially if the next document is very large.

**Comment by sandertan** [comment]
Thanks for letting me know. I'll check if this fixes my issue as well.

**Comment by tomolopolis** [comment]
Cool - if you see this happening again, the error should appear in dev tools, so please paste here if you can

**Comment by sandertan** [comment]
HI @tomolopolis , I pulled the latest build from Dockerhub, but I'm still having the issue. The API call indeed succeeds, but it fails in the frontend.

![image](https://user-images.githubusercontent.com/9624990/94902225-1d6aa300-0498-11eb-9666-279290e2d4cb.png)

I can send you the dataset, cdb and Vocab if you want to reproduce it yourself; its all public data.

**Comment by tomolopolis** [comment]
Hi Sander - looks like this is actually the server, 

yes please if you have links to the models / data etc. I can repro my side and fix

**Comment by tomolopolis** [comment]
Looks like this was a vocab.make_unigram_table error, added an error message that will surface UI side also.
https://github.com/CogStack/MedCATtrainer/commit/fc3eebf87fcc1c824f7f7cd9182ca6d824f16772
